on:
  workflow_call:
    inputs:
      app_type:
        type: string
        default: native
      sfdx:
        type: boolean
        default: false
      ios:
        type: string
        default: "26"
        description: "Space-separated iOS major versions (e.g. '17 18 26')"
      is_pr:
        type: boolean
        default: false

jobs:
  test-ios:
    name: ${{ inputs.app_type }} iOS ${{ inputs.ios }}
    runs-on: macos-26-large
    steps:
      - uses: actions/checkout@v4
        if: ${{ inputs.is_pr }}
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/checkout@v4
        if: ${{ ! inputs.is_pr }}
      - name: Install Dependencies
        env:
          IOS_UI_TEST_CONFIG: ${{ secrets.IOS_UI_TEST_CONFIG }}
        run: |
          ./install.sh
          echo $IOS_UI_TEST_CONFIG > ./shared/test/ios/ui_test_config.json
      - name: Build ${{ inputs.app_type }} and Test Login (iOS ${{ inputs.ios }})
        env:
          GITHUB_RUN_NUM: ${{ github.run_number }}
        run: |
          SFDX=""
          if ${{ inputs.sfdx }} ; then
            SFDX="--sf"
          fi

          ./test ios ${{ inputs.app_type }} --ios "${{ inputs.ios }}" ${SFDX}