on:
  workflow_call:
    inputs:
      app_type:
        type: string
        default: native
      sfdx:
        type: boolean
        default: false
      is_pr:
        type: boolean
        default: false
      complex_hybrid:
        required: false
        type: string
      ios: 
        type: string
        default: "26.0"
      xcode:
        type: string
        default: "26.0"
      macos:
        type: string
        default: macos-26
      device:
        type: string
        default: "iPhone-16"
    
jobs:
  test-ios:
    name: ${{ inputs.app_type }} iOS ${{ inputs.ios }} sfdx:${{ inputs.sfdx }} adv_auth:${{ inputs.adv_auth }} carthage:${{ inputs.carthage }} complex_hybrid:${{ inputs.complex_hybrid }}
    runs-on: ${{ inputs.macos }}
    steps:
      - uses: actions/checkout@v4
        if: ${{ inputs.is_pr }}
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/checkout@v4
        if: ${{ ! inputs.is_pr }}
      - name: Install Dependencies
        run: |
          ./install.sh
          echo $IOS_UI_TEST_CONFIG > ./shared/test/ios/ui_test_config.json
      - name: Install iOS 17 runtime if needed
        if: ${{ inputs.ios == '17.5' }}
        run: xcodes runtimes install "iOS 17.5"
      - name: Build ${{ inputs.app_type }} ${{ inputs.ios }} and Test Login
        env:
          GITHUB_RUN_NUM: ${{ github.run_number }}
        run: |
          SFDX=""

          if ${{ inputs.sfdx }} ; then
            TYPE="--sf"
          fi

          ./test ios ${TYPE}:${{ inputs.app_type }} ios:${{ inputs.ios }} device:${{ inputs.device }} ${SFDX}