name: Build and Test All Apps

on: 
  schedule:
    - cron: "0 6 * * 0"  # cron is UTC, this translates to 10 PM PST Saturday.
  # This lets us trigger the workflow from a browser.
  workflow_dispatch:

jobs:
  android-base:
    name: ${{ matrix.app }} Android
    strategy:
      fail-fast: false
      matrix:
        app:  [native, native_kotlin, hybrid_local, hybrid_remote, react_native, MobileSyncExplorerReactNative, MobileSyncExplorerKotlinTemplate, complex_hybrid_accounteditor, complex_hybrid_mobilesyncexplorer]
    uses: ./.github/workflows/android-reusable-workflow.yaml
    with:
      app: ${{ matrix.app }}
    secrets: inherit

  android-sfdx:
    name: ${{ matrix.app }} Android sfdx
    strategy:
      fail-fast: false
      matrix:
        app:  [native, hybrid_local, react_native]
    uses: ./.github/workflows/android-reusable-workflow.yaml
    with:
      app: ${{ matrix.app }}
      sfdx: true
    secrets: inherit
    
  ios-base-legacy:
    name: ${{ matrix.app }} iOS 17+18
    strategy:
      fail-fast: false
      matrix:
        app:  [native, native_swift, hybrid_local, hybrid_remote, react_native, MobileSyncExplorerReactNative, MobileSyncExplorerSwift, complex_hybrid_accounteditor, complex_hybrid_mobilesyncexplorer]
    uses: ./.github/workflows/ios-reusable-workflow.yaml
    with:
      app: ${{ matrix.app }}
      ios: "17 18"
      runner: macos-15
    secrets: inherit

  ios-base:
    name: ${{ matrix.app }} iOS 26
    strategy:
      fail-fast: false
      matrix:
        app:  [native, native_swift, hybrid_local, hybrid_remote, react_native, MobileSyncExplorerReactNative, MobileSyncExplorerSwift, complex_hybrid_accounteditor, complex_hybrid_mobilesyncexplorer]
    uses: ./.github/workflows/ios-reusable-workflow.yaml
    with:
      app: ${{ matrix.app }}
      ios: "26"
    secrets: inherit

  ios-sfdx:
    name: ${{ matrix.app }} iOS sfdx
    strategy:
      fail-fast: false
      matrix:
        app: [native, hybrid_local, react_native]
    uses: ./.github/workflows/ios-reusable-workflow.yaml
    with:
      app: ${{ matrix.app }}
      sfdx: true
    secrets: inherit

  android-upgrade:
    name: ${{ matrix.app }} Android Upgrade from ${{ matrix.upgradeFrom }}
    strategy:
      fail-fast: false
      matrix:
        app: [MobileSyncExplorerKotlin, hybrid_local, MobileSyncExplorerReactNative]
        upgradeFrom: ["12.2.0"]
    uses: ./.github/workflows/android-upgrade-reusable-workflow.yaml
    with:
      app: ${{ matrix.app }}
      upgradeFrom: ${{ matrix.upgradeFrom }}
    secrets: inherit

  ios-upgrade:
    name: ${{ matrix.app }} iOS Upgrade from ${{ matrix.upgradeFrom }}
    strategy:
      fail-fast: false
      matrix:
        app: [MobileSyncExplorerSwift, hybrid_local, MobileSyncExplorerReactNative]
        upgradeFrom: ["12.2.0"]
    uses: ./.github/workflows/ios-upgrade-reusable-workflow.yaml
    with:
      app: ${{ matrix.app }}
      upgradeFrom: ${{ matrix.upgradeFrom }}
    secrets: inherit