name: Build and Test All Apps

on: 
  schedule:
    - cron: "0 6 * * 0"  # cron is UTC, this translates to 10 PM PST Saturday.
  # This lets us trigger the workflow from a browser.
  workflow_dispatch:

jobs:
  android-base:
    name: ${{ matrix.app_type }} Android
    strategy:
      fail-fast: false
      matrix:
        app_type:  [native, native_kotlin, hybrid_local, hybrid_remote, react_native, MobileSyncExplorerReactNative, AndroidNativeLoginTemplate, complex_hybrid_accounteditor, complex_hybrid_mobilesyncexplorer]
    uses: ./.github/workflows/android-reusable-workflow.yaml
    with:
      app_type: ${{ matrix.app_type }}
    secrets: inherit

  android-sfdx:
    name: ${{ matrix.app_type }} Android sfdx
    strategy:
      fail-fast: false
      matrix:
        app_type:  [native, hybrid_local, react_native]
    uses: ./.github/workflows/android-reusable-workflow.yaml
    with:
      app_type: ${{ matrix.app_type }}
      sfdx: true
    secrets: inherit
    
  ios-base:
    name: ${{ matrix.app_type }} iOS ${{ matrix.ios }}
    strategy:
      fail-fast: false
      matrix:
        app_type:  [native, native_swift, hybrid_local, hybrid_remote, react_native, MobileSyncExplorerReactNative, MobileSyncExplorerSwift, iOSNativeLoginTemplate, complex_hybrid_accounteditor, complex_hybrid_mobilesyncexplorer]
        ios: ["26", "18", "17"]
        include:
            - ios: "26"
              xcode: "26.3"
            - ios: "18"
              xcode: "16.4"
            - ios: "17"
              xcode: "16.4"
              device: "iPhone-15"
    uses: ./.github/workflows/ios-reusable-workflow.yaml
    with:
      app_type: ${{ matrix.app_type }}
      ios: ${{ matrix.ios }}
      xcode: ${{ matrix.xcode }}
      device: ${{ matrix.device || 'iPhone-16' }}
    secrets: inherit

  ios-sfdx:
    name: ${{ matrix.app_type }} iOS sfdx
    strategy:
      fail-fast: false
      matrix:
        app_type: [native, hybrid_local, react_native]
    uses: ./.github/workflows/ios-reusable-workflow.yaml
    with:
      app_type: ${{ matrix.app_type }}
      sfdx: true
    secrets: inherit